# Generated by Django 2.1.2 on 2018-10-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Chegou', 'Chegou'), ('Realizado', 'Realizado'), ('Desmarcado', 'Desmarcado')], default='Agendado', max_length=15)),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60')], default=15, max_length=2)),
                ('priority', models.CharField(blank=True, choices=[('Ambulatorio', 'Ambulatorio'), ('Internado', 'Internado'), ('Isolamento', 'Isolamento'), ('Urgencia', 'Urgencia'), ('Idoso', 'Idoso'), ('Criança', 'Criança'), ('Deficiente', 'Deficiente')], max_length=15)),
                ('prepare', models.TextField(blank=True)),
                ('insurance', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('birth_date', models.DateField()),
                ('details', models.TextField(blank=True)),
                ('requester', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('procedures', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctors', models.ManyToManyField(to='schedule.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Procedure'),
        ),
    ]
