# Generated by Django 2.1.2 on 2018-10-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CT', 'Agendado'), ('CF', 'Confirmado'), ('WT', 'Chegou'), ('CL', 'Realizado'), ('QT', 'Desmarcado')], default='CT', max_length=2)),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default=15, max_length=2)),
                ('patient', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('AB', 'Ambulatorio'), ('IT', 'Internado'), ('IS', 'Isolamento'), ('UR', 'Urgencia'), ('OL', 'Idoso'), ('KD', 'Criança'), ('DF', 'Deficiente')], max_length=2)),
                ('prepare', models.TextField()),
                ('insurance', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('procedure', models.CharField(choices=[('0', 'Cápsula Endoscópica'), ('1', 'Colonoscopia'), ('2', 'Consulta'), ('3', 'Corpo estranho'), ('4', 'CPRE'), ('5', 'Diverticulectomia'), ('6', 'Ecoendoscopia'), ('7', 'Parecer'), ('8', 'Retorno'), ('9', 'Retosigmoidoscopia')], max_length=2)),
                ('details', models.TextField()),
                ('requester', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
