# Generated by Django 2.1.2 on 2018-11-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Chegou', 'Chegou'), ('Realizado', 'Realizado'), ('Desmarcado', 'Desmarcado')], default='Agendado', max_length=15)),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60')], default=15, max_length=2)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Ambulatorio', 'Ambulatorio'), ('Internado', 'Internado'), ('Isolamento', 'Isolamento'), ('Urgencia', 'Urgencia'), ('Idoso', 'Idoso'), ('Criança', 'Criança'), ('Deficiente', 'Deficiente')], default='Normal', max_length=15)),
                ('birth_date', models.DateField()),
                ('insurance', models.CharField(max_length=50)),
                ('insurance_number', models.CharField(blank=True, max_length=30)),
                ('cell_phone', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('prepare', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('requester', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('allergies', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('cell_phone', models.CharField(blank=True, max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('insurance', models.CharField(blank=True, max_length=50)),
                ('insurance_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('neighborhood', models.CharField(blank=True, max_length=70)),
                ('city', models.CharField(blank=True, max_length=70)),
                ('job', models.CharField(blank=True, max_length=70)),
                ('marital_status', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=15)),
                ('rg', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctors', models.ManyToManyField(to='schedule.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Procedure'),
        ),
    ]
