# Generated by Django 2.1.2 on 2018-10-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='procedures',
        ),
    ]
