# Generated by Django 2.1.2 on 2018-11-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('exam_type', models.CharField(choices=[('Antigliadina/Antiendomisio', 'Antigliadina/Antiendomisio'), ('Bilirrubina total e frações', 'Bilirrubina total e frações'), ('Cápsula Endoscópica', 'Cápsula Endoscópica'), ('COLONOSCOPIA', 'COLONOSCOPIA'), ('CPRE', 'CPRE'), ('Creatinina/Ureia', 'Creatinina/Ureia'), ('EDA', 'EDA'), ('Hemograma', 'Hemograma')], max_length=30)),
                ('result', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.MedicalRecord'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
