# Generated by Django 2.1.2 on 2018-10-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20181015_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='priority',
            field=models.CharField(choices=[('Ambulatorio', 'Ambulatorio'), ('Internado', 'Internado'), ('Isolamento', 'Isolamento'), ('Urgencia', 'Urgencia'), ('Idoso', 'Idoso'), ('Criança', 'Criança'), ('Deficiente', 'Deficiente')], max_length=15),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='procedure',
            field=models.CharField(choices=[('Cápsula Endoscópica', 'Cápsula Endoscópica'), ('Colonoscopia', 'Colonoscopia'), ('Consulta', 'Consulta'), ('Corpo estranho', 'Corpo estranho'), ('CPRE', 'CPRE'), ('Diverticulectomia', 'Diverticulectomia'), ('Ecoendoscopia', 'Ecoendoscopia'), ('Parecer', 'Parecer'), ('Retorno', 'Retorno'), ('Retosigmoidoscopia', 'Retosigmoidoscopia')], max_length=25),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Chegou', 'Chegou'), ('Realizado', 'Realizado'), ('Desmarcado', 'Desmarcado')], default='Agendado', max_length=15),
        ),
    ]
