# Generated by Django 2.1.2 on 2018-12-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20181123_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('main_complaint', models.CharField(max_length=50)),
                ('hda', models.TextField(blank=True)),
                ('pathology', models.TextField(blank=True)),
                ('comorbidities', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('alergies', models.CharField(blank=True, max_length=50)),
                ('habits', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('physical_exam', models.TextField(blank=True)),
                ('diagnostical_hypothesis', models.TextField(blank=True)),
                ('conduct', models.TextField(blank=True)),
                ('adicional_info', models.TextField(blank=True)),
                ('insurance', models.CharField(blank=True, max_length=30)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='weight',
        ),
        migrations.AddField(
            model_name='complementaryexam',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementary_exams', to='schedule.Doctor'),
        ),
        migrations.AddField(
            model_name='complementaryexam',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementary_exams', to='schedule.MedicalRecord'),
        ),
        migrations.AlterField(
            model_name='complementaryexam',
            name='exam_type',
            field=models.CharField(choices=[('Antigliadina/Antiendomisio', 'Antigliadina/Antiendomisio'), ('Bilirrubina total e frações', 'Bilirrubina total e frações'), ('Cápsula Endoscópica', 'Cápsula Endoscópica'), ('COLONOSCOPIA', 'COLONOSCOPIA'), ('CPRE', 'CPRE'), ('Creatinina/Ureia', 'Creatinina/Ureia'), ('EDA', 'EDA'), ('Hemograma', 'Hemograma'), ('LARINGOSCOPIA', 'LARINGOSCOPIA'), ('Outros', 'Outros'), ('Retossigmoidoscopia', 'Retossigmoidoscopia'), ('RMN', 'RMN'), ('RX contrastado', 'RX contrastado'), ('RX simples', 'RX simples'), ('TAP/TTPA', 'TAP/TTPA'), ('TC', 'TC'), ('TGO/TGP', 'TGO/TGP'), ('US Endoscopico', 'US Endoscopico'), ('USG abdomen', 'USG abdomen'), ('USG PÉLVICO', 'USG PÉLVICO'), ('VHS', 'VHS')], max_length=30),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='executed_exams',
            field=models.ManyToManyField(blank=True, to='schedule.ComplementaryExam'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses', to='schedule.MedicalRecord'),
        ),
    ]
