# Generated by Django 2.1.2 on 2018-10-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_doctor_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Ambulatorio', 'Ambulatorio'), ('Internado', 'Internado'), ('Isolamento', 'Isolamento'), ('Urgencia', 'Urgencia'), ('Idoso', 'Idoso'), ('Criança', 'Criança'), ('Deficiente', 'Deficiente')], max_length=15),
        ),
    ]
