# Generated by Django 2.1.2 on 2018-10-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20181019_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('procedures', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='procedure',
            field=models.CharField(choices=[('Cirurgia da cabeça e do pescoço', 'Cirurgia da cabeça e do pescoço'), ('Coloproctologia', 'Coloproctologia'), ('Gastroenterologia', 'Gastroenterologia'), ('Proctologista', 'Proctologista'), ('Ecoendoscopia', 'Ecoendoscopia'), ('Endoscopia Digestiva Alta', 'Endoscopia Digestiva Alta'), ('Colonoscopia', 'Colonoscopia'), ('Colangiografia Endoscópica Retrógrada – CPRE', 'Colangiografia Endoscópica Retrógrada – CPRE'), ('Retossigmoidoscopia', 'Retossigmoidoscopia'), ('Balão Intragástrico', 'Balão Intragástrico'), ('Manometria Anorretal', 'Manometria Anorretal'), ('pHmetria', 'pHmetria'), ('Manometria Esofágica', 'Manometria Esofágica')], max_length=25),
        ),
    ]
