# Generated by Django 2.1.2 on 2018-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20181115_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
