# Generated by Django 2.1.2 on 2018-10-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20181019_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ('date',)},
        ),
    ]
