# Generated by Django 2.1.2 on 2018-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20181024_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Ambulatorio', 'Ambulatorio'), ('Internado', 'Internado'), ('Isolamento', 'Isolamento'), ('Urgencia', 'Urgencia'), ('Idoso', 'Idoso'), ('Criança', 'Criança'), ('Deficiente', 'Deficiente')], default='Normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
