# Generated by Django 2.1.2 on 2018-10-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_patient'),
        ('schedule', '0005_auto_20181022_1846'),
    ]

    operations = [
    ]
