# Generated by Django 2.1.2 on 2018-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='nhe', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='patient',
            name='rg',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
