# Generated by Django 2.1.2 on 2018-10-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_merge_20181022_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prepare',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='priority',
            field=models.CharField(blank=True, choices=[('Ambulatorio', 'Ambulatorio'), ('Internado', 'Internado'), ('Isolamento', 'Isolamento'), ('Urgencia', 'Urgencia'), ('Idoso', 'Idoso'), ('Criança', 'Criança'), ('Deficiente', 'Deficiente')], max_length=15),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='requester',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
