# Generated by Django 2.1.2 on 2018-11-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_complementayexam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplementayExam',
            new_name='ComplementaryExam',
        ),
    ]
