# Generated by Django 2.1.2 on 2018-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20181121_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryexam',
            name='exam_type',
            field=models.CharField(choices=[('Antigliadina/Antiendomisio', 'Antigliadina/Antiendomisio'), ('Bilirrubina total e frações', 'Bilirrubina total e frações'), ('Cápsula Endoscópica', 'Cápsula Endoscópica'), ('COLONOSCOPIA', 'COLONOSCOPIA'), ('CPRE', 'CPRE'), ('Creatinina/Ureia', 'Creatinina/Ureia'), ('EDA', 'EDA'), ('Hemograma', 'Hemograma'), ('LARINGOSCOPIA', 'LARINGOSCOPIA'), ('Outros', 'Outros'), ('Retossigmoidoscopia', 'Retossigmoidoscopia'), ('RMN', 'RMN'), ('RX contrastado', 'RX contrastado'), ('RX simples', 'RX simples'), ('TAP/TTPA', 'TAP/TTPA'), ('TC', 'TC'), ('TGO/TGP', 'TGO/TGP'), ('US Endoscopico', 'US Endoscopico'), ('USG abdomen', 'USG abdomen'), ('USG PÉLVICO', 'USG PÉLVICO'), ('VHS', 'VHS')], max_length=30),
        ),
    ]
