# Generated by Django 2.1.2 on 2018-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20181212_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('json_template', models.TextField()),
            ],
        ),
    ]
