# Generated by Django 2.1.2 on 2018-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_anamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='adicional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='alergies',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='comorbidities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='conduct',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='diagnostical_hypothesis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='executed_exams',
            field=models.ManyToManyField(blank=True, to='schedule.ComplementaryExam'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='fisical_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='fisical_exams',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='habits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hda',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='insurance',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='main_complaint',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='pathology',
            field=models.TextField(blank=True),
        ),
    ]
