# Generated by Django 2.1.2 on 2018-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20181201_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='main_complaint',
            field=models.CharField(max_length=50),
        ),
    ]
