# Generated by Django 2.1.2 on 2018-12-13 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_medicalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='json_medical_report',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='medicalreporttemplate',
            name='json_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
