# Generated by Django 2.1.2 on 2018-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_patient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultation',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
