# Generated by Django 2.1.2 on 2018-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20181213_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='requester',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
