# Generated by Django 2.1.2 on 2018-12-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20181201_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Doctor'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Patient'),
        ),
    ]
