# Generated by Django 2.1.2 on 2018-12-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20181207_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='fisical_exam',
            new_name='physical_exam',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='fisical_exams',
        ),
    ]
