# Generated by Django 2.1.2 on 2019-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20190122_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecommendationtemplate',
            name='name',
            field=models.CharField(default='nhe', max_length=50),
            preserve_default=False,
        ),
    ]
