# Generated by Django 2.1.2 on 2018-12-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20181207_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='weight',
        ),
    ]
