# Generated by Django 2.1.2 on 2019-01-24 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_medicalrecommendationtemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('json_medical_statement', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Doctor')),
                ('medical_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_statement', to='schedule.MedicalRecord')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalStatementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('json_medical_recommendation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Doctor')),
            ],
        ),
    ]
