# Generated by Django 2.1.2 on 2019-01-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_medicalstatement_medicalstatementtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalstatementtemplate',
            old_name='json_medical_recommendation',
            new_name='json_medical_statement',
        ),
    ]
