# Generated by Django 2.1.2 on 2018-12-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_remove_medicalrecord_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementaryexam',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Doctor'),
        ),
        migrations.AddField(
            model_name='complementaryexam',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Patient'),
        ),
    ]
