# Generated by Django 2.1.2 on 2018-12-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20181208_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementaryexam',
            name='patient',
        ),
        migrations.AddField(
            model_name='complementaryexam',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.MedicalRecord'),
        ),
    ]
