# Generated by Django 2.1.2 on 2018-12-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20181208_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complementaryexam',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementary_exams', to='schedule.MedicalRecord'),
        ),
    ]
