# Generated by Django 2.1.2 on 2018-12-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20181208_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses', to='schedule.MedicalRecord'),
        ),
    ]
